---
version: "3.9"
services:
  prowlarr:
    image: hotio/prowlarr:testing-1.15.0.4361@sha256:33980ad91c15a20eda4c1db5af4cbe1f4f1daa4f334346e8b9ddeb2d6955d200
    container_name: prowlarr
    depends_on:
      - transmission
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/London
    volumes:
      - ./test.sh:/scripts/test.sh
      - ./config.xml:/config/config.xml
    ports:
      - 9696:9696
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9696/system/status"]
  transmission:
    image: linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    ports:
      - 9091:9091