---
version: "3.9"
services:
  prowlarr:
    image: ghcr.io/hotio/prowlarr:release-2.3.0.5236@sha256:4419f813a717ef46e87bf3a515f22f71856d258a3e551e0f794086d6a3386182
    container_name: prowlarr
    depends_on:
      - transmission
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/London
    volumes:
      - ./test.sh:/scripts/test.sh
      - ./config.xml:/config/config.xml
    ports:
      - 9696:9696
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9696/system/status"]
  transmission:
    image: linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    ports:
      - 9091:9091
